<?php

return [

    'general' => [
        //"sn" => "報名序號",
        //"bName" => "梯次",
        //"group" => "組別",
        //"number" => "座號",
        //"is_admitted" => "錄取",
        //"is_paid" => "是否已繳費",
        //"is_cancelled" => "已取消",
        //"deleted_at" => "取消日期",
        //"bank_second_barcode" => "銷帳帳號",
        //"tax_id_no" => "統一編號",
        //"region" => "區域",
        //"applied_at" => "報名日期",
        //"name" => "姓名",
        //"english_name" => "英文慣用名",
        //"gender" => "生理性別",
        //"idno" => "身分證字號",
        //"is_foreigner" => "海外身分",
        //"is_allow_notified" => "願意收到電子報",
        //"mobile" => "手機",
        //"phone_home" => "家中電話",
        // "phone_work" => "工作電話",
        // "fax" => "傳真",
        //"line" => "LineID",
        //"wechat" => "微信ID",
        //"email" => "Email",
        //"zipcode" => "郵遞區號",
        //"address" => "地址",
        //"emergency_name" => "緊急聯絡人",
        //"emergency_relationship" => "緊急聯絡人關係",
        //"emergency_mobile" => "緊急聯絡人手機",
        // "emergency_phone_home" => "緊急聯絡人家中電話",
        // "emergency_phone_work" => "緊急聯絡人工作電話",
        // "emergency_fax" => "緊急聯絡人傳真",
        //"introducer_name" => "介紹人/推薦人",
        //"introducer_relationship" => "介紹人關係",
        //"introducer_phone" => "介紹人/推薦人電話",
        //"introducer_email" => "介紹人/推薦人電子信箱",
        //"introducer_participated" => "介紹人/推薦人參加過的福智活動",
        //"portrait_agree" => "肖像權",
        //"profile_agree" => "個人資料允許",
        //"expectation" => "對活動的期望"
    ],

    'acamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "number" => "座號",
        "region" => "區域",
        "applied_at" => "報名日期",
        "is_attend" => "回覆參加",
        "name" => "姓名",
        "gender" => "生理性別",
        "participation_mode" => "參加地點",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        //"birthday" => "出生日",
        "education" => "最高學歷",
        "belief" => "宗教信仰",
        "address" => "現居住地點",
        "mobile" => "行動電話",
        "phone_work" => "公司電話",
        "phone_home" => "住家電話",
        "email" => "電子郵件",
        "unit" => "服務單位",
        "unit_county" => "服務地點-縣市",
        "unit_subarea" => "服務地點-區",
        "industry" => "產業別",
        "title" => "職稱",
        "job_property" => "工作屬性",
        "is_manager" => "是否為主管",
        "is_cadre" => "是否為儲訓主管",
        "is_technical_staff" => "是否為專門技術人員",
        "way" => "如何得知營隊",
        "motivation" => "報名動機",
        "motivation_other" => "報名動機(其它)",
        "blisswisdom_type" => "參與過福智活動",
        "blisswisdom_type_other" => "參與過福智活動(其它)",
        "class_location" => "後續課程參加地點",
        "transportation" => "交通需求",
        "emergency_name" => "緊急聯絡人姓名",
        "emergency_mobile" => "緊急聯絡人電話",
        "emergency_relationship" => "緊急聯絡人關係",
        "introducer_name" => "介紹人姓名",
        "introducer_phone" => "介紹人電話",
        "introducer_relationship" => "介紹人關係",
        "introducer_participated" => "介紹人福智班別",
        "is_inperson" => "是否本人填表",
        "agent_name" => "代填人姓名",
        "agent_phone" => "代填人電話",
        "agent_relationship" => "代填人關係",
        "portrait_agree" => "肖像權",
    ],

    'actcamp' => [
        "sn" => "報名序號",
        "applied_at" => "報名日期",
        "name" => "姓名",
        "category" => "身份別",
        "emergency_name" => "聯絡人姓名",
        "emergency_mobile" => "聯絡人電話",
        "emergency_relationship" => "關係",
        "mobile" => "行動電話",
        "email" => "電子郵件",
        "transportation" => "交通方式",
        "fee" => "活動費用",
        "is_attend" => "是否參加",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
    ],

    'actvcamp' => [
        "sn" => "報名序號",
        "applied_at" => "報名日期",
        "name" => "姓名",
        "mobile" => "行動電話",
        "email" => "電子郵件",
    ],

    'tcamp' => [
        "sn" => "報名序號",
        "applied_at" => "報名日期",
        "bName" => "梯次",
        "group" => "組別",
        "number" => "座號",
        "is_admitted" => "錄取",
        "region" => "區域",
        "name" => "姓名",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        //"education" => "最高學歷",
        "has_license" => "是否有教師證",
        "workshop_credit_type" => "研習時數類型",
        "idno" => "身分證字號",
        "is_educating" => "是否現任學校或教育單位任職",
        "school_or_course" => "任職機關/學程",
        "subject_teaches" => "任教科系/科目",
        "title" => "職稱",
        "unit" => "服務單位名稱/校名",
        "unit_county" => "服務單位所在縣市",
        "mobile" => "行動電話",
        "phone_home" => "家中電話",
        "line" => "LineID",
        "zipcode" => "郵遞區號",
        "address" => "地址",
        "email" => "Email",
        "is_allow_notified" => "願意收到電子報",
        "emergency_name" => "緊急聯絡人",
        "emergency_relationship" => "緊急聯絡人關係",
        "emergency_mobile" => "緊急聯絡人電話1",
        "emergency_phone_home" => "緊急聯絡人電話2",
        "introducer_name" => "介紹人/推薦人",
        "introducer_relationship" => "介紹人/推薦人關係",
        "introducer_phone" => "介紹人/推薦人電話",
        "introducer_participated" => "介紹人/推薦人福智班別",
        //"never_attend_any_stay_over_tcamps" => "未曾參加過住宿型福智教師生命成長營",
        "is_attend_tcamp" => "是否參加過教師營",
        "tcamp_year" => "參加教師營年度",
        "is_blisswisdom" => "是否參加過福智其它活動/是否為廣論學員",
        //"blisswisdom_type" => "參加過的福智活動(選項)",
        //"blisswisdom_type_complement" => "參加過的福智活動(其它)",
        "lrclass" => "廣論班別",
        "info_source" => "得知管道",
        "interesting" => "有興趣的主題(選項)",
        "interesting_complement" => "有興趣的主題(其它)",
        "after_camp_available_day" => "營隊後方便參加時間",
        "expectation" => "對活動的期望",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
        "transportation_depart" => "去程交通",
        "transportation_back" => "回程交通",
    ],

    'tvcamp' => [
        "name" => "姓名",
        "gender" => "生理性別",
        "unit" => "服務單位",
        "title" => "職稱",
        "mobile" => "手機",
        "line" => "LineID",
        "email" => "Email",
    ],


    'utcamp' => [
        "sn" => "報名序號",
        "applied_at" => "報名日期",
        "bName" => "梯次",
        "group" => "組別",
        "number" => "座號",
        "is_admitted" => "錄取",
        "region" => "區域",
        "name" => "姓名",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "workshop_credit_type" => "研習時數類型",
        "idno" => "身分證字號",
        "unit" => "服務單位名稱/校名",
        "unit_county" => "服務單位所在縣市",
        "department" => "服務系所/部門",
        "position" => "身份別",
        "title" => "職稱",
        "mobile" => "行動電話",
        "phone_home" => "家中電話",
        "email" => "Email",
        "info_source" => "得知管道",
        "introducer_name" => "推薦人",
        "introducer_relationship" => "推薦人關係",
        "is_allow_notified" => "願意收到電子報",
        "expectation" => "對活動的期望",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
        "transportation_depart" => "去程交通",
        "transportation_back" => "回程交通",
    ],

    'utvcamp' => [
        "name" => "姓名",
        "gender" => "生理性別",
        "unit" => "服務單位",
        "title" => "職稱",
        "mobile" => "手機",
        "line" => "LineID",
        "email" => "Email",
    ],


    'ceocamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "applied_at" => "報名日期",
        "name" => "姓名",
        "files" => "上傳的檔案",
        "english_name" => "英文慣用名",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "carers" => "關懷員",
        "introducer_name" => "推薦人",
        "introducer_participated" => "推薦人廣論研討班別",
        "introducer_phone" => "推薦人手機號碼",
        "introducer_email" => "推薦人電子信箱",
        "introducer_relationship" => "與被推薦人關係",
        "mobile" => "手機號碼",
        "email" => "電子信箱",
        "zipcode" => "郵遞區號",
        "address" => "通訊地址",
        "line" => "LineID",
        "contact_time" => "適合聯絡時段",
        "substitute_name" => "代理人姓名",
        "substitute_phone" => "代理人聯絡電話",
        "substitute_email" => "代理人電子信箱",
        "exceptional_conditions" => "特別關懷事項",
        "unit" => "公司名稱",
        "industry" => "產業別",
        "industry_other" => "產業別:自填",
        "title" => "職稱",
        "job_property" => "職務類型",
        "job_property_other" => "職務類型:自填",
        "phone_work" => "公司電話",
        "employees" => "公司員工總數",
        "direct_managed_employees" => "所轄員工人數",
        "capital" => "資本額",
        "capital_unit" => "資本額單位",
        "org_type" => "公司組織形式",
        "org_type_other" => "公司組織形式:自填",
        "years_operation" => "公司成立幾年",
        "reasons_recommend" => "特別推薦理由",
        "profile_agree" => "個人資料允許",
        "participation_mode" => "參加營隊形式",
        "is_attend" => "參加意願",
        "reasons_online" => "選擇上述參加形式的原因"
    ],

    'ceovcamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "applied_at" => "報名日期",
        "name" => "姓名",
        "english_name" => "英文慣用名",
        "avatar" => "大頭照",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "group_priority1" => "組別志願1",
        "group_priority2" => "組別志願2",
        "group_priority3" => "組別志願3",
        "lrclass" => "廣論研討班別",
        "mobile" => "手機號碼",
        "email" => "電子信箱",
        "line" => "LineID",
        "cadre_experiences" => "班級護持記錄",
        "volunteer_experiences" => "義工護持記錄",
        "transport" => "日常交通方式",
        "transport_other" => "日常交通方式:其它",
        "expertise" => "專長",
        "expertise_other" => "專長:其它",
        "language" => "語言",
        "language_other" => "語言:其它",
        "unit" => "公司名稱",
        "industry" => "產業別",
        "title" => "職稱",
        "job_property" => "職務類型",
        "employees" => "公司員工總數",
        "direct_managed_employees" => "所轄員工人數",
        "profile_agree" => "個人資料允許",
        "portrait_agree" => "肖像權",
        "introducer_name" => "邀請人"
    ],

    'ecamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "applied_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "carers" => "關懷員",
        "care_log" => "關懷記錄",
        "belief" => "宗教信仰",
        "education" => "最高學歷",
        "unit" => "服務單位",
        "unit_location" => "服務單位所在地",
        "title" => "職稱",
        "job_property" => "工作屬性",
        "experience" => "經歷",
        "employees" => "公司員工人數",
        "direct_managed_employees" => "直屬管轄人數",
        "industry" => "產業別",
        "mobile" => "手機",
        "phone_work" => "公司電話",
        "phone_home" => "家中電話",
        "line" => "LineID",
        "wechat" => "微信ID",
        "email" => "Email",
        "zipcode" => "郵遞區號",
        "address" => "地址",
        "emergency_name" => "緊急聯絡人",
        "emergency_relationship" => "緊急聯絡人關係",
        "emergency_mobile" => "緊急聯絡人電話",
        "introducer_name" => "介紹人",
        "introducer_relationship" => "介紹人關係",
        "introducer_phone" => "介紹人電話",
        "introducer_participated" => "介紹人參加過的福智活動",
        "expectation" => "對活動的期望",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
        "favored_event" => "有興趣活動",
        "is_attend" => "參加意願",
        "after_camp_available_day" => "後續課程時間",
    ],

    'evcamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "applied_at" => "報名日期",
        "name" => "姓名",
        "english_name" => "英文慣用名",
        "avatar" => "大頭照",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "group_priority1" => "組別志願1",
        "group_priority2" => "組別志願2",
        "group_priority3" => "組別志願3",
        "lrclass" => "廣論研討班別",
        "mobile" => "手機號碼",
        "email" => "電子信箱",
        "line" => "LineID",
        "cadre_experiences" => "班級護持記錄",
        "volunteer_experiences" => "義工護持記錄",
        "transport" => "日常交通方式",
        "transport_other" => "日常交通方式:其它",
        "expertise" => "專長",
        "expertise_other" => "專長:其它",
        "language" => "語言",
        "language_other" => "語言:其它",
        "participation_dates" => "可護持日期",
        "unit" => "公司名稱",
        "industry" => "產業別",
        "title" => "職稱",
        "job_property" => "職務類型",
        "employees" => "公司員工總數",
        "direct_managed_employees" => "所轄員工人數",
        "profile_agree" => "個人資料允許",
        "portrait_agree" => "肖像權",
        "introducer_name" => "邀請人"
    ],

    'hcamp' => [
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "education" => "報名者學程",
        "special_condition" => "特殊狀況",
        "traffic_depart" => "去程交通",
        "traffic_return" => "回程交通",
        // "branch_or_classroom_belongs_to" => "",
        // "class_type" => "",
        // "parent_lamrim_class" => "",
        // "is_recommended_by_reading_class" => "",
        "is_lamrim" => "父母是否參加廣論班",
        "is_child_blisswisdommed" => "孩子曾在的福智文教系統",
    ],

    'ycamp' => [
        "sn" => "報名序號",
        "is_attend" => "參加意願",
        "bName" => "梯次",
        "group" => "組別",
        "number" => "座號",
        "region" => "區域",
        "applied_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "nationality" => "國籍",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "habbit" => "興趣",
        "email" => "電子郵件",
        "system" => "課程學制",
        "day_nigh" => "部別",
        "school" => "就讀學校",
        "department" => "系所",
        "grade" => "年級",
        "mobile" => "行動電話",
        "phone_home" => "家中電話",
        "zipcode" => "郵遞區號",
        "address" => "通訊地址",
        "way" => "如何得知活動",
        "club" => "社團活動及擔任職務",
        "goal" => "這一生目標",
        "expectation" => "對活動的期望",
        "blisswisdom_type" => "曾參與福智活動",
        "blisswisdom_type_other" => "曾參與福智活動(其它)",
        "father_name" => "父親姓名",
        "father_lamrim" => "父親廣論班別",
        "father_phone" => "父親聯絡電話",
        "mother_name" => "母親姓名",
        "mother_lamrim" => "母親廣論班別",
        "mother_phone" => "母親聯絡電話",
        "introducer_name" => "介紹人姓名",
        "introducer_relationship" => "介紹人關係",
        "introducer_phone" => "介紹人電話",
        "introducer_participated" => "介紹人參加過的福智活動",
        "in_inperson" => "是否本人填表",
        "agent_name" => "代填人姓名",
        "agent_phone" => "代填人電話",
        "emergency_name" => "緊急聯絡人姓名",
        "emergency_relationship" => "緊急聯絡人關係",
        "emergency_mobile" => "緊急聯絡人電話",
        "portrait_agree" => "肖像權",
        "profile_agree" => "個人資料允許",
    ],

    'yvcamp' => [
        "name" => "姓名",
        "gender" => "生理性別",
        "unit" => "服務單位",
        "title" => "職稱",
        "mobile" => "手機",
        "line" => "LineID",
        "email" => "Email",
    ],

    'lrcamp' => [
        "sn" => "報名序號",
        "bName" => "梯次",
        "group" => "組別",
        "region" => "區域",
        "applied_at" => "報名日期",
        "name" => "姓名",
        "gender" => "生理性別",
        "birthyear" => "出生年",
        "birthmonth" => "出生月",
        "birthday" => "出生日",
        "carers" => "關懷員",
        "care_log" => "關懷記錄",
        "education" => "最高學歷",
        "unit" => "服務單位",
        "unit_location" => "服務單位所在地",
        "title" => "職稱",
        "job_property" => "工作屬性",
        "experience" => "經歷",
        "employees" => "公司員工人數",
        "direct_managed_employees" => "直屬管轄人數",
        "industry" => "產業別",
        "mobile" => "手機",
        "phone_work" => "公司電話",
        "phone_home" => "家中電話",
        "line" => "LineID",
        "wechat" => "微信ID",
        "email" => "Email",
    ],

    'lrvcamp' => [
        "name" => "姓名",
        "gender" => "生理性別",
        "unit" => "服務單位",
        "title" => "職稱",
        "mobile" => "手機",
        "line" => "LineID",
        "email" => "Email",
    ],

    'regions' => [
        'ycamp' => ['台北','桃園','新竹','台中','雲嘉','台南','高雄','海外'],
    ],

    'form_accomodation' => [
        "ycamp" => [
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "mobile" => "手機號碼",
            //底下為空格欄位
            "empty1" => "報到",
            "empty2" => "床位",
            "empty3" => "預排",
            "empty4" => "備註(遲到)",
        ],
    ],

    'form_contact' => [
        "ycamp" => [
            "empty" => "確認",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "school" => "學校",
            "department" => "系所",
            "grade" => "年級",
            "mobile" => "手機號碼",
            "email" => "電子郵件",
        ],
    ],

    //交通確認表(各組)
    'form_traffic_confirm' => [
        "ycamp" => [
            "empty" => "確認",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "depart_from" => "去程交通",
            "back_to" => "回程交通",
            "fare" => "應交車資",
            "deposit" => "已交車資",
        ],
    ],

    'form_checkin' => [
        "ycamp" => [
            "admitted_no" => "錄取編號",
            "sn" => "報名序號",
            "name" => "姓名",
            "school" => "學校",
            "department" => "系所",
            "is_checkin" => "是否報到",
        ],
    ],

    //交通總表
    'form_traffic' => [
        "ycamp" => [
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "depart_from" => "去程交通",
            "back_to" => "回程交通",
            "fare" => "應交車資",
            "deposit" => "已交車資",
            "cash" => "現金繳納",
            "is_attend" => "參加意願",
            "is_checkin" => "是否報到",
            "notes" => "備註",              //非remark
            "applicant_id" => "報名序號",
        ],
    ],

    //搭車表(各上車處)
    'form_traffic_loc' => [
        "ycamp" => [
            "no" => "編號",
            "empty" => "簽到",
            "admitted_no" => "錄取編號",
            "name" => "姓名",
            "gender" => "性別",
            "mobile" => "手機",
            "deposit" => "已交車資",
        ],
    ],

    'display' => [
        'acamp' => [
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "公司名稱",
                "sort" => 0,
                "for_query" => 0,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 0,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],

        'avcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],

        'actcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "category" => [
                "name" => "身份別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "emergency_name" => [
                "name" => "聯絡人姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "emergency_mobile" => [
                "name" => "聯絡人電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "emergency_relationship" => [
                "name" => "關係",
                "sort" => 0,
                "for_query" => 0,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
            "transportation" => [
                "name" => "交通方式",
                "sort" => 1,
                "for_query" => 1,
            ],
            "fee" => [
                "name" => "活動費用",
                "sort" => 1,
                "for_query" => 1,
            ],
            "is_attend" => [
                "name" => "是否參加",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],

        'actvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
        ],

        'ceocamp' => [
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "files" => [
                "name" => "上傳的檔案",
                "sort" => 0,
                "for_query" => 0,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "公司名稱",
                "sort" => 0,
                "for_query" => 0,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 0,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "carer" => [
                "name" => "關懷員",
                "sort" => 1,
                "for_query" => 0,
            ],
            "is_attend" => [
                "name" => "參加意願",
                "sort" => 1,
                "for_query" => 0,
            ],
            "participation_mode" => [
                "name" => "參加形式",
                "sort" => 1,
                "for_query" => 1,
            ],
            "reasons_recommend" => [
                "name" => "推薦理由",
                "sort" => 0,
                "for_query" => 0,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],

        'ceovcamp' => [
            "batch" => [
                "name" => "報名梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "avatar" => [
                "name" => "照片",
                "sort" => 0,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "lrclass" => [
                "name" => "班別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "公司名稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "volunteer_experiences" => [
                "name" => "義工護持記錄",
                "sort" => 0,
                "for_query" => 1,
            ],
            "cadre_experiences" => [
                "name" => "班級護持記錄",
                "sort" => 0,
                "for_query" => 1,
            ],
            "expertise" => [
                "name" => "專長",
                "sort" => 0,
                "for_query" => 1,
            ],
            "transport" => [
                "name" => "交通方式",
                "sort" => 0,
                "for_query" => 1,
            ],
            "group_priority" => [
                "name" => "志願組別",
                "sort" => 1,
                "for_query" => 0,
            ],
        ],

        'ecamp' => [
            "id" => [
                "name" => "報名序號",
                "sort" => 1,
                "for_query" => 0,
            ],
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "carer" => [
                "name" => "關懷員",
                "sort" => 1,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            //            "age" => [
            //                "name" => "年齡",
            //                "sort" => 1,
            //                "for_query" => 0,
            //            ],
            "files" => [
                "name" => "上傳的檔案",
                "sort" => 0,
                "for_query" => 0,
            ],
            "birthdate" => [
                "name" => "出生年月日",
                "sort" => 1,
                "for_query" => 0,
            ],
            "unit" => [
                "name" => "服務單位",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit_location" => [
                "name" => "服務單位所在地",
                "sort" => 1,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "手機",
                "sort" => 0,
                "for_query" => 0,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 1,
                "for_query" => 0,
            ],
            "zipcode" => [
                "name" => "郵遞區號",
                "sort" => 1,
                "for_query" => 1,
            ],
            "address" => [
                "name" => "地址",
                "sort" => 1,
                "for_query" => 1,
            ],
            "is_attend" => [
                "name" => "參加意願",
                "sort" => 1,
                "for_query" => 0,
            ],
            "after_camp_available_day" => [
                "name" => "後續課程時間",
                "sort" => 1,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],

        'evcamp' => [
            "batch" => [
                "name" => "報名梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "roles" => [
                "name" => "職務組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "職務",
                "sort" => 1,
                "for_query" => 0,
            ],
            "avatar" => [
                "name" => "照片",
                "sort" => 0,
                "for_query" => 0,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "lrclass" => [
                "name" => "班別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "industry" => [
                "name" => "產業別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "公司名稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "volunteer_experiences" => [
                "name" => "義工護持記錄",
                "sort" => 0,
                "for_query" => 1,
            ],
            "participation_dates" => [
                "name" => "可護持日期",
                "sort" => 0,
                "for_query" => 1,
            ],
            "expertise" => [
                "name" => "專長",
                "sort" => 0,
                "for_query" => 1,
            ],
            "transport" => [
                "name" => "交通方式",
                "sort" => 0,
                "for_query" => 1,
            ],
            "group_priority" => [
                "name" => "志願組別",
                "sort" => 1,
                "for_query" => 0,
            ],
            "participation_dates" => [
                "name" => "可護持日期",
                "sort" => 1,
                "for_query" => 0,
            ],
        ],

        'tcamp' => [
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "服務單位名稱/校名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit_county" => [
                "name" => "服務單位所在縣市",
                "sort" => 1,
                "for_query" => 1,
            ],
            "department" => [
                "name" => "服務系所/部門",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "身份別",
                "sort" => 0,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],

        'utvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "生理性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "服務單位",
                "sort" => 1,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "手機",
                "sort" => 0,
                "for_query" => 1,
            ],
            "line" => [
                "name" => "LineID",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 0,
                "for_query" => 1,
            ]
        ],

        'tvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "生理性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "服務單位",
                "sort" => 1,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "手機",
                "sort" => 0,
                "for_query" => 1,
            ],
            "line" => [
                "name" => "LineID",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "Email",
                "sort" => 0,
                "for_query" => 1,
            ]
        ],

        'actvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
        ],

        'utcamp' => [
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit" => [
                "name" => "服務單位名稱/校名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "unit_county" => [
                "name" => "服務單位所在縣市",
                "sort" => 1,
                "for_query" => 1,
            ],
            "department" => [
                "name" => "服務系所/部門",
                "sort" => 1,
                "for_query" => 1,
            ],
            "position" => [
                "name" => "身份別",
                "sort" => 0,
                "for_query" => 1,
            ],
            "title" => [
                "name" => "職稱",
                "sort" => 0,
                "for_query" => 1,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],

        'actvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 1,
                "for_query" => 1,
            ],
            "mobile" => [
                "name" => "行動電話",
                "sort" => 0,
                "for_query" => 1,
            ],
            "email" => [
                "name" => "電子郵件",
                "sort" => 0,
                "for_query" => 1,
            ],
        ],

        'ycamp' => [
            "batch" => [
                "name" => "梯次",
                "sort" => 1,
                "for_query" => 0,
            ],
            "group" => [
                "name" => "組別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "age" => [
                "name" => "年齡",
                "sort" => 1,
                "for_query" => 1,
            ],
            "school_location" => [
                "name" => "學校所在地",
                "sort" => 1,
                "for_query" => 1,
            ],
            "school" => [
                "name" => "學校",
                "sort" => 1,
                "for_query" => 1,
            ],
            "department" => [
                "name" => "系別",
                "sort" => 1,
                "for_query" => 1,
            ],
            "grade" => [
                "name" => "年級",
                "sort" => 1,
                "for_query" => 1,
            ],
            "introducer_name" => [
                "name" => "推薦人",
                "sort" => 0,
                "for_query" => 1,
            ],
            "contactlog" => [
                "name" => "關懷記錄",
                "sort" => 0,
                "for_query" => 0,
            ],
        ],
        'yvcamp' => [
            "name" => [
                "name" => "姓名",
                "sort" => 0,
                "for_query" => 1,
            ],
            "gender" => [
                "name" => "性別",
                "sort" => 1,
                "for_query" => 1,
            ],
        ],
    ]
];
